sudo: required
node_js:
  - "11.10.1"
services:
  - docker

before_install:
  - docker build -t jmirecki/udemy-docker-frontend -f Dockerfile.dev .

script:
  - docker run jmirecki/udemy-docker-frontend npm run test -- --coverage
